
name: "Push docker image to GCR"
description: "Push docker image to Google container registry"

branding:
  icon: "upload-cloud"
  color: "red"
  
inputs:
  root_name:
    description: The image root name
    required: true
    default: ''
  image_name: 
    description: Image name
    required: true
  image_tag:
    description: Tag name
    required: false
    default: latest
  gcp_registry: 
    description: Google container registry
    required: false
    default: ''
  project_id: 
    description: Google project
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Tag and push
      shell: bash
      run: |
        docker image ls
