
name: "Push docker image to GCP"
description: "Push docker image to"

branding:
  icon: "upload-cloud"
  color: "red"
  
inputs:
  root_name:
    description: The image root name
    required: true
    default: teg
  image_name: 
    description: Image name
    required: true
    default: default-image-name
  image_tag:
    description: Tag name
    required: false
    default: latest
  dockerfile:
    description: Dockerfile that will build the image
    required: true
    default: ""
  context:
    description: Docker build context
    required: false
    default: '.'

runs:
  using: 'docker'
  image: 'Dockerfile'