
name: "Push docker image to GCR"
description: "Push docker image to Google container registry"

branding:
  icon: "upload-cloud"
  color: "red"
  
inputs:
  root_name:
    description: The image root name
    required: true
    default: ''
  image_name: 
    description: Image name
    required: true
  image_tag:
    description: Tag name
    required: false
    default: latest
  gcp_registry: 
    description: Google container registry
    required: false
    default: ''
  project_id: 
    description: Google project
    required: false
    default: ''
  gcr_service_key:
    description: GCP authentication
    required: true
    default: ''

runs:
  using: docker
  image: Dockerfile

# runs:
#   using: "composite"
#   steps:
#     - name: Tag and push
#       shell: bash
#       run: |
#         docker login -u ${{inputs.gcr_service_key}}  --password-stdin https://${{inputs.gcp_registry}}/
#         docker tag '${{inputs.root_name}}/${{inputs.image_name}}:latest' '${{inputs.gcp_registry}}/${{inputs.project_id}}/${{inputs.root_name}}/${{inputs.image_name}}:${{inputs.image_tag}}' 

#         docker push '${{inputs.gcp_registry}}/${{inputs.project_id}}/${{inputs.root_name}}/${{inputs.image_name}}:${{inputs.image_tag}}' 