
name: "Push docker image to GCP"
description: "Push docker image to"

branding:
  icon: "upload-cloud"
  color: "red"
  
inputs:
  root_name:
    description: The image root name
    required: true
    default: ''
  image_name: 
    description: Image name
    required: true
    default: ''
  image_tag:
    description: Tag name
    required: true
    default: latest
  image_cloud:
    description: Image cloud name
    required: true
    default: ''


runs:
  using: "composite"
  steps:
    - name: Build
      shell: bash
      run: |
        docker tag '${{ inputs.image_name }}' '${{ inputs.image_cloud }}'
        docker push '${{ inputs.image_cloud }}'
