
name: "Push docker image to GCP"
description: "Push docker image to"

branding:
  icon: "upload-cloud"
  color: "red"
  
inputs:
  root_name:
    description: The image root name
    required: true
  image_name: 
    description: Image name
    required: true
  image_tag:
    description: Tag name
    required: false
    default: latest


runs:
  using: 'docker'
  image: 'Dockerfile'