
name: "Build docker image"
description: "Build docker image"

branding:
  icon: "upload-cloud"
  color: "red"
  
inputs:
  root_name:
    description: The image root name
    required: true
    default: teg
  image_name: 
    description: Image name
    required: true
    default: default-image-name
  image_tag:
    description: Tag name
    required: false
    default: latest
  dockerfile:
    description: Dockerfile that will build the image
    required: true
    default: ""
  context:
    description: Docker build context
    required: false
    default: '.'
  target:
    description: Mutli-staged build target
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Build
      shell: bash
      run: |
        docker build -f '{{ inputs.dockerfile }}' -t '${{inputs.root_name}}/${{inputs.image_name}}:${{inputs.image_tag}}' --rm ./teg
