  
name: Push to GCR GitHub Action
description: An action that build docker image and push to Google Cloud Registry
inputs:
  gcloud_service_key:
    description: Google cloud service key as json
    required: true
  registry:
    description: The registry where the image should be pushed
    required: false
    default: 'eu.gcr.io'
  project_id:
    description: The project id
    required: true
    default: example-project
  image_name:
    description: The image name
    required: true
    default: example-image-name
  image_tag:
    description: Tag name
    required: false
    default: latest
  dockerfile:
    description: Dockerfile that will build the image
    required: false
    default: ""
  context:
    description: Docker build context
    required: false
    default: '.'
  target:
    description: Mutli-staged build target
    required: false
    default: ""
  build_args:
    description: "Pass a list of env vars as build-args for docker-build, separated by commas"
    required: false
runs:
  using: docker
  image: Dockerfile